"""The arrangement -> compilation boundary (Sprint 22).

WHERE THE DECLARATIVE LAYER MEETS THE GEOMETRY PIPELINE, and nowhere else.
`resolve.py` turns an arrangement into explicit placements and has no opinion
about what can be built; this module answers the separate question "which of
these placements does the CURRENT pipeline actually emit as geometry?", and
records the answer per instance.

WHY THE TWO ARE SEPARATE FUNCTIONS. Resolution must stay a pure function of the
arrangement, so its output is stable across pipeline versions and can be stored,
compared and fingerprinted. Generation capability changes as JewelMind grows.
Fusing them would make a stored resolution depend on which release resolved it.

THE HONEST EXECUTION BOUNDARY. Today's pipeline builds ONE stone component
(`stone_reference`), placed on the design axis by `geometry/stone/builder.py`.
So:

- exactly one instance — the primary CENTER one — maps to that component and is
  reported `GENERATED`;
- every additional instance is reported `NOT_GENERATED` with the reason;
- nothing is silently dropped, and no placeholder solid is invented.

That is a genuine PARTIAL, recorded as such in the capability registry and in
docs/bible/24-arrangement/execution-boundary.md. Reporting these instances as
generated, or emitting an empty component to make a count match, would both be
the fabrication the brief forbids.

KERNEL-FREE, LIKE THE REST OF THE PACKAGE. This module decides names and
statuses. It never imports CadQuery, never builds a shape, and never calls a
geometry builder — Atlas does that, using the plan this module produces.
"""

from __future__ import annotations

from jewelmind.arrangement.capability import ARRANGEMENT_CAPABILITIES
from jewelmind.arrangement.models import (
    ArrangementDefinition,
    ResolvedArrangement,
    ResolvedInstance,
)
from jewelmind.arrangement.resolve import resolve_arrangement

#: The component name a generated primary stone takes.
#:
#: UNCHANGED from every previous sprint, and that is the point: a single-stone
#: design must keep producing a component called exactly `stone_reference`, or
#: every Golden baseline, preview manifest, exporter, inspection check and
#: frontend consumer would need to change at once.
PRIMARY_STONE_COMPONENT = "stone_reference"

#: How an additional instance's component would be named once multi-stone
#: emission exists. Defined HERE rather than at the point of emission so the
#: naming contract is fixed and testable before any geometry depends on it, and
#: so `geometry/roles.py` can classify such a name correctly the moment one
#: appears.
STONE_INSTANCE_COMPONENT_PREFIX = f"{PRIMARY_STONE_COMPONENT}."


def stone_component_name(instance_id: str, *, is_primary: bool) -> str:
    """The geometry component name for a resolved instance.

    The primary instance keeps the bare, historical name. Any other instance
    gets `stone_reference.<instanceId>`, which is:

    - traceable — the component names the instance it came from, so identity is
      never positional (INSPECT-GOV-015);
    - classifiable — `geometry/roles.py` recognizes the prefix, so an additional
      stone is a stone_reference and stays excluded from production exports by
      default (LAW-006), rather than falling through to the
      `production_metal` default and being fused into metal;
    - stable — derived from the authoritative ID, so it does not change when the
      instance list is reordered.
    """

    if is_primary:
        return PRIMARY_STONE_COMPONENT
    return f"{STONE_INSTANCE_COMPONENT_PREFIX}{instance_id}"


def _primary_instance(resolved: ResolvedArrangement) -> ResolvedInstance | None:
    """The one instance the current pipeline can build.

    Selection is deterministic and does NOT use list position: the first
    `CENTER`-role instance by sorted ID, or the first instance by sorted ID when
    no instance claims that role. Choosing `instances[0]` would make the built
    geometry depend on serialization order, which is exactly the dependency this
    layer exists to remove.
    """

    if not resolved.instances:
        return None
    centers = [i for i in resolved.instances if i.role == "CENTER"]
    pool = centers or list(resolved.instances)
    return min(pool, key=lambda i: i.instanceId)


def _not_generated_note(instance: ResolvedInstance) -> str:
    """Why this instance produced no geometry. Specific, not generic.

    A reader must be able to tell "the pipeline cannot yet emit a second stone"
    from "your arrangement is wrong", because the two need completely different
    responses.
    """

    if instance.sourcePatternId is not None:
        origin = f"generated by pattern {instance.sourcePatternId!r}"
    else:
        origin = "declared explicitly"
    return (
        f"Placement resolved ({origin}), but no geometry was built: the current "
        "pipeline emits one stone component per model. Multi-stone geometry is "
        "PARTIAL — see docs/bible/24-arrangement/execution-boundary.md."
    )


def compile_arrangement(
    definition: ArrangementDefinition | None,
) -> ResolvedArrangement | None:
    """Resolve an arrangement and mark what the current pipeline generates.

    Returns `None` for `None`, which is the whole backward-compatibility story
    in one line: a design with no arrangement compiles to no arrangement and
    behaves exactly as it did before this sprint. It does NOT synthesize a
    one-instance arrangement for a single-stone design, because that would
    invent a declaration the document never made.
    """

    if definition is None:
        return None

    resolved = resolve_arrangement(definition)
    primary = _primary_instance(resolved)

    instances: list[ResolvedInstance] = []
    generated = 0
    notes: list[str] = []

    for instance in resolved.instances:
        is_primary = primary is not None and instance.instanceId == primary.instanceId
        if is_primary and instance.stoneRef == "primary":
            instances.append(
                instance.model_copy(
                    update={
                        "generationStatus": "GENERATED",
                        "generationNote": None,
                        "componentName": stone_component_name(
                            instance.instanceId, is_primary=True
                        ),
                    }
                )
            )
            generated += 1
            continue

        if instance.stoneRef != "primary":
            # An unresolved stone reference is reported here rather than raised:
            # the arrangement is structurally fine, and Forge's JM-ARRANGE rules
            # are where an unresolvable reference becomes a validation finding.
            note = (
                f"Instance {instance.instanceId!r} references stone "
                f"{instance.stoneRef!r}; only 'primary' resolves today, so no "
                "geometry was built for it."
            )
        else:
            note = _not_generated_note(instance)

        instances.append(
            instance.model_copy(
                update={
                    "generationStatus": "NOT_GENERATED",
                    "generationNote": note,
                    "componentName": None,
                }
            )
        )
        notes.append(note)

    return resolved.model_copy(
        update={
            "instances": instances,
            "generatedCount": generated,
            "notes": notes,
        }
    )


def multi_stone_generation_status() -> str:
    """The capability status the rest of the system should report.

    Read from `capability.py` rather than restated, so a future sprint that
    implements emission flips this everywhere by changing one registry entry.
    """

    return ARRANGEMENT_CAPABILITIES["multi_stone_geometry"].status
