"""The 9 verbatim INTENT_* diagnostic codes.

Unlike Designer's error model, none of these ever fails the HTTP request
— an unresolved or conflicting intent is a normal, expected outcome, not
a backend failure. See docs/bible/13-design-intent/358-intent-diagnostics.md.
"""

from __future__ import annotations

INTENT_UNKNOWN_DESCRIPTOR = "INTENT_UNKNOWN_DESCRIPTOR"
INTENT_AMBIGUOUS_DESCRIPTOR = "INTENT_AMBIGUOUS_DESCRIPTOR"
INTENT_CONFLICT = "INTENT_CONFLICT"
INTENT_UNSUPPORTED_TARGET = "INTENT_UNSUPPORTED_TARGET"
INTENT_NO_DETERMINISTIC_RESOLUTION = "INTENT_NO_DETERMINISTIC_RESOLUTION"
INTENT_PROFILE_UNAVAILABLE = "INTENT_PROFILE_UNAVAILABLE"
INTENT_RESOLUTION_REQUIRES_CONFIRMATION = "INTENT_RESOLUTION_REQUIRES_CONFIRMATION"
INTENT_INVALID_RELATION = "INTENT_INVALID_RELATION"
INTENT_PRESERVED_UNRESOLVED = "INTENT_PRESERVED_UNRESOLVED"

ALL_INTENT_DIAGNOSTIC_CODES = (
    INTENT_UNKNOWN_DESCRIPTOR,
    INTENT_AMBIGUOUS_DESCRIPTOR,
    INTENT_CONFLICT,
    INTENT_UNSUPPORTED_TARGET,
    INTENT_NO_DETERMINISTIC_RESOLUTION,
    INTENT_PROFILE_UNAVAILABLE,
    INTENT_RESOLUTION_REQUIRES_CONFIRMATION,
    INTENT_INVALID_RELATION,
    INTENT_PRESERVED_UNRESOLVED,
)
