"""Keeps specs/designer/v1/ honest against the real backend implementation.

Mirrors test_vision_schemas.py / test_studio_schemas.py / test_foundry_registry.py:
every example and test-vector file here was generated by actually running
DesignerService with FakeDesignerProvider (see backend/generate_designer_specs.py),
never hand-invented — this file only re-validates schema/example consistency
and re-derives a couple of the same results live, so a future pipeline
change that silently breaks a documented example is caught here.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.designer.provider import FakeDesignerProvider
from jewelmind.designer.schemas import NaturalLanguageDesignRequest, RawDesignerResponse, RawProposedValue
from jewelmind.designer.service import DesignerService

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "designer" / "v1"

SCHEMA_FILES = [
    "natural-language-request.schema.json",
    "proposed-field.schema.json",
    "clarification-question.schema.json",
    "unsupported-feature.schema.json",
    "designer-diagnostic.schema.json",
    "design-proposal.schema.json",
    "designer-result.schema.json",
]

EXAMPLE_FILES = [
    "minimal-supported-request.json",
    "complete-solitaire-request.json",
    "ambiguous-request.json",
    "missing-required-information.json",
    "unsupported-halo-request.json",
    "mixed-supported-unsupported-request.json",
]

TEST_VECTOR_FILES = [
    "intent-mapping-vectors.json",
    "defaulting-vectors.json",
    "ambiguity-vectors.json",
    "clarification-vectors.json",
    "unsupported-feature-vectors.json",
    "proposal-to-jdl-vectors.json",
    "provenance-vectors.json",
]


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        schema = _load_json(SPECS_DIR / name)
        jsonschema.Draft202012Validator.check_schema(schema)


def test_all_example_files_exist_and_are_valid_json():
    for name in EXAMPLE_FILES:
        _load_json(SPECS_DIR / "examples" / name)


def test_all_test_vector_files_exist_and_are_valid_json():
    for name in TEST_VECTOR_FILES:
        _load_json(SPECS_DIR / "test-vectors" / name)


def test_every_example_result_validates_against_designer_result_and_design_proposal_schemas():
    result_schema = _load_json(SPECS_DIR / "designer-result.schema.json")
    proposal_schema = _load_json(SPECS_DIR / "design-proposal.schema.json")
    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        jsonschema.validate(example, result_schema)
        jsonschema.validate(example["proposal"], proposal_schema)


def test_every_natural_language_request_field_in_examples_matches_request_schema():
    # Examples store the *result*, not the request, but every request used to
    # generate them satisfies the request schema — spot-checked here by
    # reconstructing a minimal equivalent request shape.
    schema = _load_json(SPECS_DIR / "natural-language-request.schema.json")
    jsonschema.validate(
        {"requestId": "spot-check", "text": "Vorrei platino.", "interactionMode": "CREATE"}, schema
    )


def test_complete_solitaire_example_is_reproducible_live():
    example = _load_json(SPECS_DIR / "examples" / "complete-solitaire-request.json")
    service = DesignerService(
        provider=FakeDesignerProvider(
            response=RawDesignerResponse(
                proposedCanonicalValues=[
                    RawProposedValue(field="material.metal", value="oro rosa", sourceText="oro rosa"),
                    RawProposedValue(field="setting.prongCount", value="sei", sourceText="sei griffe"),
                    RawProposedValue(field="band.profile", value="comfort", sourceText="fascia comfort fit"),
                ]
            )
        )
    )
    result = service.interpret(
        NaturalLanguageDesignRequest(
            requestId="reproduce-01",
            text=example["proposal"]["sourceText"],
            interactionMode="CREATE",
        )
    )
    assert result.proposal.candidateJDL.model_dump(mode="json") == example["proposal"]["candidateJDL"]
    assert result.proposal.proposalStatus == example["proposal"]["proposalStatus"]


def test_defaulting_vector_matches_live_schema_defaults():
    vectors = _load_json(SPECS_DIR / "test-vectors" / "defaulting-vectors.json")
    vector = vectors["vectors"][0]
    assert vector["result"]["proposal"]["candidateJDL"] == vector["expectedCandidateJDL"]
