"""Keeps specs/stone/v1/ honest against the real backend implementation.

Mirrors test_shank_schemas.py (Sprint 17): every example, test-vector, and
the shape registry were generated by actually running the real
`geometry.stone.builder.build_stone()`/`domain.stone_dimensions`/
`geometry.stone.capability` code (see backend/generate_stone_specs.py, run
once and not part of the shipped code or test suite), never hand-invented
— this file re-validates schema/example consistency and re-derives
examples live to catch pipeline drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import pytest

from jewelmind.domain.defaults import default_definition
from jewelmind.domain.schema import StoneSpec
from jewelmind.geometry.stone.builder import build_stone
from jewelmind.geometry.stone.capability import STONE_SHAPE_CAPABILITIES

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "stone" / "v1"

SCHEMA_FILES = [
    "stone-definition.schema.json",
    "stone-dimensions.schema.json",
    "stone-orientation.schema.json",
    "stone-shape-capability.schema.json",
    "stone-reference-profile.schema.json",
]

EXAMPLE_FILES = [
    "round.json",
    "oval.json",
    "pear.json",
    "emerald.json",
    "cushion.json",
    "princess.json",
    "marquise.json",
]

VECTOR_FILES = [
    "shape-normalization-vectors.json",
    "dimension-vectors.json",
    "orientation-vectors.json",
    "invalid-stone-vectors.json",
    "backward-compatibility-vectors.json",
]


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        jsonschema.Draft202012Validator.check_schema(_load(SPECS_DIR / name))


def test_all_examples_validate_against_stone_definition_schema():
    schema = _load(SPECS_DIR / "stone-definition.schema.json")
    for name in EXAMPLE_FILES:
        jsonschema.validate(_load(SPECS_DIR / "examples" / name), schema)


def test_all_vector_files_exist_and_are_non_empty():
    for name in VECTOR_FILES:
        vectors = _load(SPECS_DIR / "test-vectors" / name)
        assert "vectors" in vectors
        assert len(vectors["vectors"]) > 0


def test_shape_registry_matches_the_real_capability_registry_live():
    registry = _load(SPECS_DIR / "shape-registry.json")
    live = {cap.shape: json.loads(cap.model_dump_json()) for cap in STONE_SHAPE_CAPABILITIES.values()}
    recorded = {entry["shape"]: entry for entry in registry["shapes"]}
    assert set(live) == set(recorded)
    for shape, live_entry in live.items():
        assert recorded[shape] == live_entry


def test_shape_registry_entries_validate_against_capability_schema():
    schema = _load(SPECS_DIR / "stone-shape-capability.schema.json")
    registry = _load(SPECS_DIR / "shape-registry.json")
    for entry in registry["shapes"]:
        jsonschema.validate(entry, schema)


def test_registry_never_marks_a_non_generatable_shape_as_current():
    registry = _load(SPECS_DIR / "shape-registry.json")
    for entry in registry["shapes"]:
        if entry["status"] == "current":
            assert entry["generationSupported"] is True, entry["shape"]


def test_only_round_is_setting_compatibility_supported():
    """STONE-GOV-009: stone generation capability is never conflated with
    Setting compatibility."""

    registry = _load(SPECS_DIR / "shape-registry.json")
    supported = [e["shape"] for e in registry["shapes"] if e["currentSettingCompatibility"] == "SUPPORTED"]
    assert supported == ["round"]


def test_all_seven_target_shapes_are_present_and_current():
    registry = _load(SPECS_DIR / "shape-registry.json")
    shapes = {e["shape"] for e in registry["shapes"] if e["status"] == "current"}
    assert shapes == {"round", "oval", "pear", "emerald", "cushion", "princess", "marquise"}


@pytest.mark.parametrize("name", EXAMPLE_FILES)
def test_example_reproduces_live(name):
    example = _load(SPECS_DIR / "examples" / name)
    d = default_definition()
    d.stone = StoneSpec.model_validate(example["stone"])
    component = build_stone(d)
    assert component.metadata["shape"] == example["generatedMetadata"]["shape"]
    assert round(component.volume_mm3, 6) == example["volumeMm3"]
    assert component.metadata["lengthMm"] == example["generatedMetadata"]["lengthMm"]
    assert component.metadata["widthMm"] == example["generatedMetadata"]["widthMm"]


def test_dimension_vectors_match_live_resolution():
    from jewelmind.domain.stone_dimensions import (
        resolved_depth_mm,
        resolved_length_mm,
        resolved_width_mm,
    )

    vectors = _load(SPECS_DIR / "test-vectors" / "dimension-vectors.json")
    for vector in vectors["vectors"]:
        stone = StoneSpec.model_validate(vector["input"])
        assert resolved_length_mm(stone) == vector["resolvedLengthMm"]
        assert resolved_width_mm(stone) == vector["resolvedWidthMm"]
        assert resolved_depth_mm(stone) == vector["resolvedDepthMm"]


def test_invalid_stone_vectors_are_actually_rejected():
    from pydantic import ValidationError

    vectors = _load(SPECS_DIR / "test-vectors" / "invalid-stone-vectors.json")
    for vector in vectors["vectors"]:
        with pytest.raises(ValidationError) as caught:
            StoneSpec.model_validate(vector["input"])

        # Also assert the RECORDED message still matches the real one. Without
        # this the `expectedError` field is documentation nothing verifies, and
        # it had in fact drifted: it still listed only the seven Sprint 18
        # shapes after Sprint 20 added fourteen more.
        assert caught.value.errors()[0]["msg"] == vector["expectedError"], (
            f"recorded expectedError for {vector['description']!r} no longer "
            "matches the real validator output"
        )


def test_backward_compatibility_vector_reproduces_the_pre_sprint18_volume():
    vectors = _load(SPECS_DIR / "test-vectors" / "backward-compatibility-vectors.json")
    for vector in vectors["vectors"]:
        d = default_definition()
        d.stone = StoneSpec.model_validate(vector["input"])
        component = build_stone(d)
        assert round(component.volume_mm3, 6) == vector["expectedVolumeMm3"]
