"""Keeps specs/shank/v1/ honest against the real backend implementation.

Mirrors test_geometry_inspection_schemas.py: every example, test-vector,
and the capability registry were generated by actually running the real
`geometry.shank.builder.build_shank()`/`geometry.shank.taper`/
`geometry.shank.capability` code (see backend/generate_shank_specs.py, run
once and not part of the shipped code or test suite), never hand-invented
— this file re-validates schema/example consistency and re-derives one
example live to catch pipeline drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.domain.defaults import default_definition
from jewelmind.geometry.shank.builder import build_shank
from jewelmind.geometry.shank.capability import SHANK_CAPABILITIES

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "shank" / "v1"

SCHEMA_FILES = [
    "shank-definition.schema.json",
    "section-profile.schema.json",
    "width-function.schema.json",
    "thickness-function.schema.json",
    "taper-definition.schema.json",
    "connection-interface.schema.json",
]

EXAMPLE_FILES = [
    "uniform-comfort-fit.json",
    "uniform-flat.json",
    "tapered-width.json",
    "tapered-thickness.json",
    "combined-taper.json",
]

VECTOR_FILES = [
    "profile-vectors.json",
    "width-function-vectors.json",
    "thickness-function-vectors.json",
    "taper-vectors.json",
    "compatibility-vectors.json",
    "invalid-shank-vectors.json",
]


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        schema = _load(SPECS_DIR / name)
        jsonschema.Draft202012Validator.check_schema(schema)


def test_all_examples_validate_against_shank_definition_schema():
    schema = _load(SPECS_DIR / "shank-definition.schema.json")
    for name in EXAMPLE_FILES:
        example = _load(SPECS_DIR / "examples" / name)
        jsonschema.validate(example, schema)


def test_all_vector_files_exist_and_are_valid_json():
    for name in VECTOR_FILES:
        vectors = _load(SPECS_DIR / "test-vectors" / name)
        assert "vectors" in vectors
        assert len(vectors["vectors"]) > 0


def test_capability_registry_matches_the_real_capability_registry_live():
    registry = _load(SPECS_DIR / "capability-registry.json")
    live = {cap.capability: json.loads(cap.model_dump_json()) for cap in SHANK_CAPABILITIES.values()}
    recorded = {entry["capability"]: entry for entry in registry["capabilities"]}
    assert set(live) == set(recorded)
    for capability, live_entry in live.items():
        assert recorded[capability] == live_entry


def test_capability_registry_never_lists_a_planned_capability_as_generatable():
    registry = _load(SPECS_DIR / "capability-registry.json")
    for entry in registry["capabilities"]:
        if entry["status"] == "planned":
            assert entry["generatable"] is False
            assert entry["jdlExposed"] is False


def test_only_toward_bottom_taper_mode_is_current():
    registry = _load(SPECS_DIR / "capability-registry.json")
    current = {e["capability"] for e in registry["capabilities"] if e["status"] == "current"}
    assert "width_taper_toward_bottom" in current
    assert "thickness_taper_toward_bottom" in current
    assert "taper_toward_head" not in current


def test_uniform_comfort_fit_example_reproduces_live():
    example = _load(SPECS_DIR / "examples" / "uniform-comfort-fit.json")
    definition = default_definition()
    component = build_shank(definition)
    assert component.metadata["variation"] == example["generatedMetadata"]["variation"] == "UNIFORM"
    assert component.metadata["sectionCount"] == example["generatedMetadata"]["sectionCount"] == 1
    assert round(component.volume_mm3, 6) == example["volumeMm3"]


def test_tapered_width_example_reproduces_live():
    example = _load(SPECS_DIR / "examples" / "tapered-width.json")
    definition = default_definition()
    definition.band.widthTaper.mode = "TOWARD_BOTTOM"
    definition.band.widthTaper.bottomRatio = 0.6
    component = build_shank(definition)
    assert component.metadata["variation"] == "TAPERED"
    live_samples = component.metadata["widthSamplesMm"]
    example_samples = example["generatedMetadata"]["widthSamplesMm"]
    assert live_samples["headMm"] == example_samples["headMm"]
    assert live_samples["bottomMm"] == example_samples["bottomMm"]
