"""Keeps specs/setting/v1/ honest against the real backend implementation.

Every example, test-vector and the setting registry were generated by
actually running the real Setting System code (see backend/gen_setting_specs.py,
run once and not part of the shipped code or test suite), never hand-invented.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import jsonschema
import pytest

from jewelmind.domain.defaults import default_definition
from jewelmind.domain.schema import SettingType, StoneSpec
from jewelmind.geometry.assemblies.solitaire import build_solitaire_ring
from jewelmind.geometry.components.stone import build_stone_reference
from jewelmind.geometry.setting_adapter import setting_definition_from_jdl
from jewelmind.setting.capability import (
    RESERVED_SETTING_FAMILIES,
    SETTING_CAPABILITIES,
    compatibility_matrix,
)
from jewelmind.setting.dispatch import generate_setting
from jewelmind.setting.placement import prong_positions
from jewelmind.setting.stone_interface import build_stone_setting_reference

SPECS = Path(__file__).resolve().parents[2] / "specs" / "setting" / "v1"

SCHEMA_FILES = [
    "setting-definition.schema.json",
    "setting-capability.schema.json",
    "prong-setting.schema.json",
    "prong-placement.schema.json",
    "bezel-setting.schema.json",
    "setting-attachment.schema.json",
    "setting-registry.schema.json",
]

EXAMPLE_FILES = [
    "round-4-prong.json",
    "round-6-prong.json",
    "oval-prong.json",
    "round-bezel.json",
    "oval-bezel.json",
]

VECTOR_FILES = [
    "prong-placement-vectors.json",
    "compatibility-vectors.json",
    "bezel-vectors.json",
    "unsupported-combination-vectors.json",
    "backward-compatibility-vectors.json",
]


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _definition(shape="round", setting_type="prong", prong_count=6, length=8.0, width=6.0):
    d = default_definition()
    if shape != "round":
        d.stone = StoneSpec.model_validate(
            {"shape": shape, "length": length, "width": width, "depth": 4.0}
        )
    d.setting.type = setting_type
    d.setting.prongCount = prong_count
    return d


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        jsonschema.Draft202012Validator.check_schema(_load(SPECS / name))


def test_all_example_and_vector_files_exist_and_are_non_empty():
    for name in EXAMPLE_FILES:
        assert _load(SPECS / "examples" / name)
    for name in VECTOR_FILES:
        data = _load(SPECS / "test-vectors" / name)
        assert data["vectors"]


def test_setting_registry_matches_the_live_capability_registry():
    registry = _load(SPECS / "setting-registry.json")
    live = {c.settingType: json.loads(c.model_dump_json()) for c in SETTING_CAPABILITIES.values()}
    recorded = {e["settingType"]: e for e in registry["settings"]}
    assert set(live) == set(recorded)
    for setting_type, entry in live.items():
        assert recorded[setting_type] == entry


def test_registry_entries_validate_against_the_capability_schema():
    schema = _load(SPECS / "setting-capability.schema.json")
    for entry in _load(SPECS / "setting-registry.json")["settings"]:
        jsonschema.validate(entry, schema)


def test_registry_reserved_families_match_the_live_tuple():
    registry = _load(SPECS / "setting-registry.json")
    assert registry["reservedFamilies"] == list(RESERVED_SETTING_FAMILIES)


def test_registry_compatibility_matrix_matches_live():
    registry = _load(SPECS / "setting-registry.json")
    assert registry["compatibilityMatrix"] == compatibility_matrix()


def test_registry_setting_types_match_the_jdl_enum():
    """The registry must not advertise a family JDL cannot express, nor omit
    one JDL accepts."""

    from typing import get_args

    registry = _load(SPECS / "setting-registry.json")
    assert {e["settingType"] for e in registry["settings"]} == set(get_args(SettingType))


def test_no_registry_entry_claims_professional_validation():
    for entry in _load(SPECS / "setting-registry.json")["settings"]:
        assert entry["professionalValidationStatus"] == "NOT_REVIEWED"
        assert entry["seatSupport"] == "PLANNED"
        assert entry["bearingSupport"] == "PLANNED"
        assert entry["cutterSupport"] == "PLANNED"


@pytest.mark.parametrize("name", EXAMPLE_FILES)
def test_examples_validate_against_the_setting_definition_schema(name):
    """No `$ref` resolver is needed: the sub-schemas are inlined under
    `$defs`, matching this codebase's specs convention of avoiding
    cross-file `$ref`."""

    schema = _load(SPECS / "setting-definition.schema.json")
    example = _load(SPECS / "examples" / name)
    jsonschema.validate(example["settingDefinition"], schema)


@pytest.mark.parametrize(
    "name,shape,setting_type,count",
    [
        ("round-4-prong.json", "round", "prong", 4),
        ("round-6-prong.json", "round", "prong", 6),
        ("oval-prong.json", "oval", "prong", 6),
        ("round-bezel.json", "round", "bezel", 6),
        ("oval-bezel.json", "oval", "bezel", 6),
    ],
)
def test_examples_reproduce_live(name, shape, setting_type, count):
    example = _load(SPECS / "examples" / name)
    d = _definition(shape=shape, setting_type=setting_type, prong_count=count)
    components, result = generate_setting(setting_definition_from_jdl(d, build_stone_reference(d)))
    comp = next(iter(components.values()))
    recorded = example["generatedComponent"]
    assert comp.name == recorded["componentId"]
    assert round(comp.volume_mm3, 6) == recorded["volumeMm3"]
    assert len(comp.shape.Solids()) == recorded["solidCount"]
    assert result.compatibilityStatus == example["settingGeometryResult"]["compatibilityStatus"]


def test_prong_placement_vectors_reproduce_live():
    vectors = _load(SPECS / "test-vectors" / "prong-placement-vectors.json")
    for vector in vectors["vectors"]:
        d = _definition(
            shape=vector["stoneShape"],
            length=vector["lengthMm"],
            width=vector["widthMm"],
        )
        ref = build_stone_setting_reference(d.stone, build_stone_reference(d))
        positions, strategy = prong_positions(ref, vector["prongCount"], vector["prongRadiusMm"])
        assert strategy == vector["strategy"]
        assert len(positions) == len(vector["positions"])
        for (x, y), recorded in zip(positions, vector["positions"], strict=True):
            assert round(x, 9) == recorded["x"]
            assert round(y, 9) == recorded["y"]


def test_bezel_vectors_reproduce_live():
    vectors = _load(SPECS / "test-vectors" / "bezel-vectors.json")
    for vector in vectors["vectors"]:
        d = _definition(
            shape=vector["stoneShape"],
            setting_type="bezel",
            length=vector["lengthMm"],
            width=vector["widthMm"],
        )
        components, result = generate_setting(
            setting_definition_from_jdl(d, build_stone_reference(d))
        )
        bezel = components["bezel"]
        assert round(bezel.volume_mm3, 6) == vector["volumeMm3"]
        assert len(bezel.shape.Solids()) == vector["solidCount"]
        assert bezel.metadata["stepSafetyRepairApplied"] == vector["stepSafetyRepairApplied"]
        assert result.compatibilityStatus == vector["compatibility"]


def test_backward_compatibility_vector_reproduces_live():
    vectors = _load(SPECS / "test-vectors" / "backward-compatibility-vectors.json")
    for vector in vectors["vectors"]:
        model = build_solitaire_ring(default_definition())
        # Exact: primitive-built prong geometry is bit-identical everywhere.
        assert model.components["prongs"].volume_mm3 == vector["expectedProngVolumeMm3"]
        # Tolerance: an OCCT boolean-fuse volume carries real platform-dependent
        # drift (~6.7e-14 relative between this repo's Windows and CI's Linux
        # build). See `test_setting.py::BOOLEAN_VOLUME_REL_TOL`.
        assert math.isclose(
            model.combined_metal_volume_mm3,
            vector["expectedCombinedMetalVolumeMm3"],
            rel_tol=1e-9,
        ), (
            f"{model.combined_metal_volume_mm3!r} != "
            f"{vector['expectedCombinedMetalVolumeMm3']!r}"
        )
        assert model.setting_result.placementStrategy == vector["expectedPlacementStrategy"]


def test_compatibility_vectors_match_live():
    vectors = _load(SPECS / "test-vectors" / "compatibility-vectors.json")
    assert vectors["vectors"] == compatibility_matrix()
