"""Keeps specs/design-intent/v1/ honest against the real backend implementation.

Mirrors test_designer_schemas.py: every example and test-vector file here
was generated by actually running `build_design_intent()` and the real
vocabulary module (see backend/generate_design_intent_specs.py, run once
and not part of the shipped code or test suite), never hand-invented —
this file re-validates schema/example consistency and re-derives one
example live to catch pipeline drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.design_intent.resolver import RawStatementInput, build_design_intent

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "design-intent" / "v1"

SCHEMA_FILES = [
    "intent-target.schema.json",
    "intent-statement.schema.json",
    "intent-relation.schema.json",
    "intent-diagnostic.schema.json",
    "intent-resolution.schema.json",
    "intent-profile.schema.json",
    "design-intent.schema.json",
]

DESIGN_INTENT_EXAMPLE_FILES = [
    "delicate-solitaire.json",
    "bold-solitaire.json",
    "minimal-classic-solitaire.json",
    "balanced-solitaire.json",
    "conflicting-intent.json",
    "unresolved-aesthetic-intent.json",
]

TEST_VECTOR_FILES = [
    "descriptor-normalization-vectors.json",
    "target-resolution-vectors.json",
    "conflict-vectors.json",
    "preservation-vectors.json",
    "intent-diff-vectors.json",
    "deterministic-resolution-vectors.json",
]


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        schema = _load_json(SPECS_DIR / name)
        jsonschema.Draft202012Validator.check_schema(schema)


def test_vocabulary_file_exists_and_has_no_numeric_cad_mapping():
    vocabulary = _load_json(SPECS_DIR / "vocabulary.json")
    assert "concepts" in vocabulary
    text = json.dumps(vocabulary)
    for forbidden in ("mm", "band.width", "stone.diameter", "prongDiameter"):
        assert forbidden not in text


def test_design_intent_examples_validate_against_schema():
    schema = _load_json(SPECS_DIR / "design-intent.schema.json")
    for name in DESIGN_INTENT_EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        jsonschema.validate(example, schema)


def test_modify_example_before_and_after_both_validate():
    schema = _load_json(SPECS_DIR / "design-intent.schema.json")
    example = _load_json(SPECS_DIR / "examples" / "modify-existing-intent.json")
    jsonschema.validate(example["before"], schema)
    jsonschema.validate(example["after"], schema)


def test_all_test_vector_files_exist_and_are_valid_json():
    for name in TEST_VECTOR_FILES:
        _load_json(SPECS_DIR / "test-vectors" / name)


def test_deterministic_resolution_vectors_never_show_a_numeric_mapping():
    vectors = _load_json(SPECS_DIR / "test-vectors" / "deterministic-resolution-vectors.json")
    for vector in vectors["vectors"]:
        assert vector["resolutionStatus"] in ("PRESERVED", "CONFLICTING")


def _without_generated_ids(intent_dict: dict) -> dict:
    # intentId/relationId are uuid4-based (deliberately non-deterministic —
    # see docs/bible/13-design-intent/332-intent-domain-model.md), so a
    # reproducibility check must ignore them and compare everything else.
    return {
        **intent_dict,
        "statements": [{k: v for k, v in s.items() if k != "intentId"} for s in intent_dict["statements"]],
    }


def test_delicate_solitaire_example_is_reproducible_live():
    example = _load_json(SPECS_DIR / "examples" / "delicate-solitaire.json")
    intent = build_design_intent(
        example["sourceText"],
        "CREATE",
        None,
        [RawStatementInput(target="ring", concept="VISUAL_WEIGHT", value="delicato", sourceText="delicato")],
        [],
    )
    live = json.loads(intent.model_dump_json())
    assert _without_generated_ids(live) == _without_generated_ids(example)
