"""Keeps specs/geometry-inspection/v2/ honest against the real backend
implementation.

Mirrors test_conversation_schemas.py and test_professional_validation_specs.py:
every example and test-vector file here was generated by actually running
the real `inspect_model()` pipeline (see
backend/generate_inspection_specs.py, run once and not part of the
shipped code or test suite), never hand-invented — this file re-validates
schema/example consistency and re-derives one example live to catch
pipeline drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.domain.defaults import default_definition
from jewelmind.geometry.assemblies.solitaire import build_solitaire_ring
from jewelmind.geometry.inspection import inspect_model

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "geometry-inspection" / "v2"

SCHEMA_FILES = [
    "geometric-fact.schema.json",
    "component-inspection.schema.json",
    "assembly-inspection.schema.json",
    "connectivity-result.schema.json",
    "intersection-result.schema.json",
    "distance-result.schema.json",
    "inspection-report.schema.json",
    "inspection-diagnostic.schema.json",
    "inspection-version.schema.json",
]

EXAMPLE_FILES_VALIDATED_AGAINST_REPORT_SCHEMA = [
    "default-solitaire-inspection.json",
    "four-prong-inspection.json",
    "failed-inspection-example.json",
]


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        schema = _load_json(SPECS_DIR / name)
        jsonschema.Draft202012Validator.check_schema(schema)


def test_report_examples_validate_against_inspection_report_schema():
    schema = _load_json(SPECS_DIR / "inspection-report.schema.json")
    for name in EXAMPLE_FILES_VALIDATED_AGAINST_REPORT_SCHEMA:
        example = _load_json(SPECS_DIR / "examples" / name)
        jsonschema.validate(example, schema)


def test_fact_registry_exists_and_has_no_professional_thresholds():
    registry = _load_json(SPECS_DIR / "fact-registry.json")
    assert "facts" in registry
    assert len(registry["facts"]) == 16
    text = json.dumps(registry)
    for forbidden in ("manufacturable", "acceptable tolerance", "industry standard"):
        assert forbidden not in text.lower()


def test_all_test_vector_files_exist_and_are_non_empty():
    vector_files = [
        "component-presence-vectors.json",
        "solid-count-vectors.json",
        "connectivity-vectors.json",
        "intersection-vectors.json",
        "distance-vectors.json",
        "stone-separation-vectors.json",
        "determinism-vectors.json",
        "regression-vectors.json",
    ]
    for name in vector_files:
        data = _load_json(SPECS_DIR / "test-vectors" / name)
        assert "vectors" in data
        assert len(data["vectors"]) > 0


def test_determinism_vectors_show_equivalent_facts_across_two_runs():
    vectors = _load_json(SPECS_DIR / "test-vectors" / "determinism-vectors.json")["vectors"]
    assert len(vectors) == 2
    assert vectors[0]["componentCount"] == vectors[1]["componentCount"]
    assert vectors[0]["productionConnectedGroups"] == vectors[1]["productionConnectedGroups"]
    assert vectors[0]["bandVolumeMm3"] == vectors[1]["bandVolumeMm3"]


def test_default_solitaire_example_is_reproducible_live():
    example = _load_json(SPECS_DIR / "examples" / "default-solitaire-inspection.json")
    model = build_solitaire_ring(default_definition())
    live = json.loads(inspect_model(model).model_dump_json())

    # inspectionId/timestamps are deliberately non-deterministic; strip
    # them before comparing, matching the same discipline used for
    # ConversationResult reproducibility checks in Sprint 12.
    def strip(report: dict) -> dict:
        report = dict(report)
        for key in ("inspectionId", "startedAt", "completedAt", "performance"):
            report.pop(key, None)
        report["geometricFacts"] = [{**f, "generatedAt": None} for f in report["geometricFacts"]]
        return report

    assert strip(live) == strip(example)
