"""Keeps specs/conversation/v1/ honest against the real backend implementation.

Mirrors test_designer_schemas.py and test_design_intent_schemas.py: every
example and test-vector file here was generated by actually running the
real ConversationEngine and its supporting modules (see
backend/generate_conversation_specs.py, run once and not part of the
shipped code or test suite), never hand-invented — this file re-validates
schema/example consistency and re-derives one flow live to catch pipeline
drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.conversation.schemas import ConversationTurnRequest
from jewelmind.conversation.service import ConversationEngine
from jewelmind.design_intent.schemas import DesignIntent
from jewelmind.designer.provider import FakeDesignerProvider
from jewelmind.designer.schemas import RawDesignerResponse, RawProposedValue
from jewelmind.designer.service import DesignerService
from jewelmind.domain.schema import JewelryDefinition

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "conversation" / "v1"

SCHEMA_FILES = [
    "conversation-action.schema.json",
    "clarification-thread.schema.json",
    "clarification-answer.schema.json",
    "conversation-state.schema.json",
    "turn-context.schema.json",
    "conversation-turn.schema.json",
    "conversation-summary.schema.json",
    "conversation-session.schema.json",
    "conversation-result.schema.json",
]

EXAMPLE_FILES = [
    "create-and-refine.json",
    "intent-only-refinement.json",
    "clarification-flow.json",
    "correction-flow.json",
    "unsupported-request-flow.json",
    "preserve-unspecified-values.json",
    "cancelled-proposal-flow.json",
]

TEST_VECTOR_FILES = [
    "state-transition-vectors.json",
    "reference-resolution-vectors.json",
    "clarification-resolution-vectors.json",
    "correction-vectors.json",
    "preservation-vectors.json",
    "context-compaction-vectors.json",
    "stale-context-vectors.json",
]

DEFAULT_INTENT = DesignIntent(sourceText="")


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        schema = _load_json(SPECS_DIR / name)
        jsonschema.Draft202012Validator.check_schema(schema)


def test_conversation_result_examples_validate_against_schema():
    result_schema = _load_json(SPECS_DIR / "conversation-result.schema.json")
    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        assert "turns" in example
        for turn_result in example["turns"]:
            jsonschema.validate(turn_result, result_schema)


def test_sessions_within_examples_validate_against_session_schema():
    session_schema = _load_json(SPECS_DIR / "conversation-session.schema.json")
    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        for turn_result in example["turns"]:
            jsonschema.validate(turn_result["session"], session_schema)


def test_turns_within_examples_validate_against_turn_schema():
    turn_schema = _load_json(SPECS_DIR / "conversation-turn.schema.json")
    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        for turn_result in example["turns"]:
            jsonschema.validate(turn_result["turn"], turn_schema)


def test_all_test_vector_files_exist_and_are_valid_json():
    for name in TEST_VECTOR_FILES:
        data = _load_json(SPECS_DIR / "test-vectors" / name)
        if name == "context-compaction-vectors.json":
            # A before/after sample of build_turn_context(), not a flat
            # "vectors" array like every other file here — see its own
            # fields (maxRecentTurnsInContext, sampledContexts, ...).
            assert "sampledContexts" in data
            assert len(data["sampledContexts"]) > 0
            continue
        assert "vectors" in data
        assert len(data["vectors"]) > 0


def test_state_transition_vectors_validate_against_schema():
    state_schema = _load_json(SPECS_DIR / "conversation-state.schema.json")
    vectors = _load_json(SPECS_DIR / "test-vectors" / "state-transition-vectors.json")
    for vector in vectors["vectors"]:
        jsonschema.validate(vector, state_schema)


def test_examples_show_genuinely_distinct_per_turn_state():
    """Regression guard for the mutable-session snapshotting pitfall
    documented in specs/conversation/v1/README.md — every turn in a
    multi-turn example must show its own turn count, not a copy of the
    final session's."""

    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        turn_counts = [len(t["session"]["turns"]) for t in example["turns"]]
        assert turn_counts == sorted(turn_counts), name
        assert turn_counts == list(range(1, len(turn_counts) + 1)), name


def _strip_generated(result_dict: dict) -> dict:
    """Removes uuid4-based ids and wall-clock timestamps so a live
    re-derivation can be compared against a previously-generated example
    (mirrors _without_generated_ids in test_design_intent_schemas.py)."""

    session = dict(result_dict["session"])
    session.pop("sessionId", None)
    session.pop("createdAt", None)
    session.pop("updatedAt", None)
    session["turns"] = [_strip_turn(t) for t in session.get("turns", [])]
    if session.get("activeProposal") is not None:
        proposal = dict(session["activeProposal"])
        proposal.pop("proposalId", None)
        proposal.pop("turnId", None)
        if proposal.get("designerProposal") is not None:
            designer_proposal = dict(proposal["designerProposal"])
            designer_proposal.pop("proposalId", None)
            proposal["designerProposal"] = designer_proposal
        session["activeProposal"] = proposal
    if session.get("pendingClarification") is not None:
        session["pendingClarification"] = _strip_clarification(session["pendingClarification"])

    return {"session": session, "turn": _strip_turn(dict(result_dict["turn"]))}


def _strip_turn(turn_dict: dict) -> dict:
    turn = dict(turn_dict)
    turn.pop("turnId", None)
    turn.pop("timestamp", None)
    turn.pop("proposalId", None)
    if turn.get("clarification") is not None:
        turn["clarification"] = _strip_clarification(turn["clarification"])
    return turn


def _strip_clarification(clarification_dict: dict) -> dict:
    clarification = dict(clarification_dict)
    clarification.pop("clarificationId", None)
    clarification.pop("originatingTurnId", None)
    clarification.pop("createdAt", None)
    clarification.pop("resolvedAt", None)
    return clarification


def test_create_and_refine_example_is_reproducible_live():
    example = _load_json(SPECS_DIR / "examples" / "create-and-refine.json")

    provider = FakeDesignerProvider(
        responses_by_text={
            "Fammi un solitario in oro rosa con sei griffe.": RawDesignerResponse(
                proposedCanonicalValues=[
                    RawProposedValue(field="material.metal", value="oro rosa"),
                    RawProposedValue(field="setting.prongCount", value="sei"),
                ]
            ),
            "Fallo in platino.": RawDesignerResponse(
                proposedCanonicalValues=[RawProposedValue(field="material.metal", value="platino")]
            ),
        }
    )
    engine = ConversationEngine(designer_service=DesignerService(provider=provider))

    def run(text: str, session=None):
        request = ConversationTurnRequest(
            text=text,
            currentJDL=JewelryDefinition(),
            currentDesignIntent=DEFAULT_INTENT,
            session=session.model_copy(deep=True) if session is not None else None,
        )
        result = engine.process_turn(request)
        return result.model_copy(deep=True)

    r1 = run("Fammi un solitario in oro rosa con sei griffe.")
    r2 = run("ok", session=r1.session)
    r3 = run("Fallo in platino.", session=r2.session)

    live = [
        _strip_generated(json.loads(r1.model_dump_json())),
        _strip_generated(json.loads(r2.model_dump_json())),
        _strip_generated(json.loads(r3.model_dump_json())),
    ]
    recorded = [_strip_generated(t) for t in example["turns"]]
    assert live == recorded
