"""Keeps specs/jewelry-architecture/v1/ and specs/ring/v2/ honest against
the real backend implementation — mirrors test_geometry_quality_schemas.py.
Every example/vector here was generated by actually running the real
`ring_definition_from_jdl()`/`generate_for_category()` code
(see backend/generate_ring_architecture_specs.py, run once and not part
of the shipped code or test suite), never hand-invented.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.domain.defaults import default_definition
from jewelmind.jewelry_category.registry import CATEGORY_CAPABILITIES
from jewelmind.ring.adapter import ring_definition_from_jdl

REPO_ROOT = Path(__file__).resolve().parents[2]
ARCH_DIR = REPO_ROOT / "specs" / "jewelry-architecture" / "v1"
RING_DIR = REPO_ROOT / "specs" / "ring" / "v2"


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_jewelry_architecture_schemas_are_valid_json_schema():
    names = (
        "jewelry-category.schema.json",
        "category-capability.schema.json",
        "category-contract.schema.json",
    )
    for name in names:
        jsonschema.Draft202012Validator.check_schema(_load(ARCH_DIR / name))


def test_all_ring_v2_schemas_are_valid_json_schema():
    for name in (
        "ring-definition.schema.json",
        "ring-sizing.schema.json",
        "shank-definition.schema.json",
        "shoulder-definition.schema.json",
        "head-definition.schema.json",
        "stone-arrangement.schema.json",
        "ring-component.schema.json",
        "ring-family.schema.json",
    ):
        jsonschema.Draft202012Validator.check_schema(_load(RING_DIR / name))


def test_category_registry_matches_the_real_capability_registry_live():
    registry = _load(ARCH_DIR / "category-registry.json")
    live = {cap.category: cap.model_dump() for cap in CATEGORY_CAPABILITIES.values()}
    recorded = {entry["category"]: entry for entry in registry["categories"]}
    assert set(live) == set(recorded)
    for category, live_capability in live.items():
        assert recorded[category] == live_capability


def test_category_registry_entries_validate_against_schema():
    schema = _load(ARCH_DIR / "category-capability.schema.json")
    registry = _load(ARCH_DIR / "category-registry.json")
    for entry in registry["categories"]:
        jsonschema.validate(entry, schema)


def test_only_ring_is_generation_supported_in_the_registry():
    registry = _load(ARCH_DIR / "category-registry.json")
    supported = [e["category"] for e in registry["categories"] if e["generationSupported"]]
    assert supported == ["ring"]


def test_ring_examples_validate_against_ring_definition_schema():
    schema = _load(RING_DIR / "ring-definition.schema.json")
    for name in ("current-default-solitaire.json", "four-prong-solitaire.json", "flat-band-solitaire.json"):
        jsonschema.validate(_load(RING_DIR / "examples" / name), schema)


def test_default_solitaire_ring_definition_example_is_reproducible_live():
    live = ring_definition_from_jdl(default_definition()).model_dump()
    recorded = _load(RING_DIR / "examples" / "current-default-solitaire.json")
    assert live == recorded


def test_all_ring_test_vector_files_exist_and_are_non_empty():
    for name in (
        "category-boundary-vectors.json",
        "solitaire-migration-vectors.json",
        "component-composition-vectors.json",
        "category-extension-vectors.json",
    ):
        data = _load(RING_DIR / "test-vectors" / name)
        assert "vectors" in data
        assert len(data["vectors"]) > 0
