"""Keeps specs/professional-validation/v1/ honest against the real backend
implementation. Mirrors test_conversation_schemas.py/test_design_intent_schemas.py:
every example and test-vector file here was generated by actually
constructing and validating the real Pydantic models (see
backend/generate_professional_validation_specs.py, run once and not part
of the shipped code or test suite), never hand-invented.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema

from jewelmind.professional_validation.schemas import ValidationRecord

SPECS_DIR = Path(__file__).resolve().parents[2] / "specs" / "professional-validation" / "v1"

SCHEMA_FILES = [
    "reviewer.schema.json",
    "reviewer-qualification.schema.json",
    "validation-scope.schema.json",
    "review-session.schema.json",
    "review-case.schema.json",
    "review-observation.schema.json",
    "validation-decision.schema.json",
    "validation-evidence.schema.json",
    "validation-record.schema.json",
    "review-package-manifest.schema.json",
]

EXAMPLE_FILES = [
    "empty-rule-review.json",
    "empty-geometry-review.json",
    "conditional-validation-example.json",
    "rejected-validation-example.json",
]

TEST_VECTOR_FILES = [
    "status-transition-vectors.json",
    "scope-vectors.json",
    "qualification-vectors.json",
    "version-impact-vectors.json",
    "disagreement-vectors.json",
    "expiration-vectors.json",
]


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_all_schema_files_exist_and_are_valid_json_schema():
    for name in SCHEMA_FILES:
        schema = _load_json(SPECS_DIR / name)
        jsonschema.Draft202012Validator.check_schema(schema)


def test_single_record_examples_validate_against_validation_record_schema():
    schema = _load_json(SPECS_DIR / "validation-record.schema.json")
    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        jsonschema.validate(example, schema)


def test_conflicting_review_example_validates_both_records():
    schema = _load_json(SPECS_DIR / "validation-record.schema.json")
    example = _load_json(SPECS_DIR / "examples" / "conflicting-review-example.json")
    assert len(example["records"]) == 2
    for record in example["records"]:
        jsonschema.validate(record, schema)


def test_every_example_record_is_marked_as_a_template():
    """The critical invariant from the Sprint 13 brief, item 59: an
    example/template record must be structurally distinguishable from a
    real one — every example here must have isTemplate: true."""

    for name in EXAMPLE_FILES:
        example = _load_json(SPECS_DIR / "examples" / name)
        assert example["isTemplate"] is True, name

    conflicting = _load_json(SPECS_DIR / "examples" / "conflicting-review-example.json")
    for record in conflicting["records"]:
        assert record["isTemplate"] is True


def test_all_test_vector_files_exist_and_are_valid_json():
    for name in TEST_VECTOR_FILES:
        data = _load_json(SPECS_DIR / "test-vectors" / name)
        assert "vectors" in data
        assert len(data["vectors"]) > 0


def test_status_transition_vectors_only_use_real_status_values():
    from typing import get_args

    from jewelmind.professional_validation.schemas import ValidationStatus

    valid = set(get_args(ValidationStatus))
    vectors = _load_json(SPECS_DIR / "test-vectors" / "status-transition-vectors.json")
    for vector in vectors["vectors"]:
        assert vector["from"] in valid
        assert vector["to"] in valid


def test_scope_vectors_reproduce_live_via_scope_matches():
    from jewelmind.professional_validation.schemas import ValidationScope
    from jewelmind.professional_validation.scope import scope_matches

    vectors = _load_json(SPECS_DIR / "test-vectors" / "scope-vectors.json")
    for vector in vectors["vectors"]:
        scope = ValidationScope.model_validate(vector["scope"])
        assert scope_matches(scope, vector["context"]) == vector["matches"]


def test_active_registry_is_reproducibly_empty():
    registry = _load_json(SPECS_DIR / "current-validation-registry.json")
    assert registry["records"] == []
    for entry in registry["records"]:
        ValidationRecord.model_validate(entry)  # would run if non-empty; documents intent
