"""Turn context construction and deterministic summarization.

See docs/bible/14-conversation/375-turn-context-model.md,
387-context-window-policy.md, and 388-history-compaction-model.md.
`ConversationSummary` is always built from real structured turn fields —
never generated by an LLM (389-conversation-summary-model.md).
"""

from __future__ import annotations

from jewelmind.conversation.schemas import (
    ConversationSession,
    ConversationSummary,
    ConversationTurn,
    TurnContext,
)

# A turn-count bound, not a token budget — this codebase never invents a
# provider-specific token measurement it can't actually verify (see
# 387-context-window-policy.md). Recent, structurally-relevant turns take
# priority over older prose.
MAX_RECENT_TURNS_IN_CONTEXT = 6


def build_turn_context(session: ConversationSession, model_state: str) -> TurnContext:
    needs_summary = len(session.turns) > MAX_RECENT_TURNS_IN_CONTEXT
    return TurnContext(
        activeProposalId=session.activeProposal.proposalId if session.activeProposal else None,
        pendingClarificationQuestion=(
            session.pendingClarification.question if session.pendingClarification else None
        ),
        recentAcceptedChanges=list(session.acceptedChangeHistory[-MAX_RECENT_TURNS_IN_CONTEXT:]),
        compactConversationSummary=compact_summary(session) if needs_summary else None,
        modelCurrentOrStale=model_state,  # type: ignore[arg-type]
    )


def compact_summary(session: ConversationSession) -> ConversationSummary:
    """Deterministically rebuilds a `ConversationSummary` from the turns
    that have scrolled out of the "recent" window — never asks an LLM to
    summarize. Structured state (accepted JDL, DesignIntent, an open
    clarification, an active proposal) is never itself summarized away;
    only prose-level history is compacted. See 388's explicit rule."""

    has_older_turns = len(session.turns) > MAX_RECENT_TURNS_IN_CONTEXT
    older_turns = session.turns[:-MAX_RECENT_TURNS_IN_CONTEXT] if has_older_turns else []

    accepted_decisions: list[str] = list(session.summary.acceptedDecisions)
    unresolved_questions: list[str] = list(session.summary.unresolvedQuestions)
    rejected_directions: list[str] = list(session.summary.rejectedDirections)
    unsupported_discussed: list[str] = list(session.summary.unsupportedDiscussed)
    intent_themes: list[str] = list(session.summary.intentThemes)

    for turn in older_turns:
        if turn.accepted and turn.technicalChanges:
            for change in turn.technicalChanges:
                if change not in accepted_decisions:
                    accepted_decisions.append(change)
        if turn.intentChanges:
            for change in turn.intentChanges:
                if change not in intent_themes:
                    intent_themes.append(change)
        if turn.interpretedAction == "REJECT_PROPOSAL" and turn.sourceText not in rejected_directions:
            rejected_directions.append(turn.sourceText)
        if turn.unsupportedFeatures:
            for feature in turn.unsupportedFeatures:
                if feature not in unsupported_discussed:
                    unsupported_discussed.append(feature)
        if turn.clarification is not None and turn.clarification.status == "OPEN":
            if turn.clarification.question not in unresolved_questions:
                unresolved_questions.append(turn.clarification.question)

    return ConversationSummary(
        acceptedDecisions=accepted_decisions,
        intentThemes=intent_themes,
        unresolvedQuestions=unresolved_questions,
        rejectedDirections=rejected_directions,
        unsupportedDiscussed=unsupported_discussed,
    )


def recent_turns(session: ConversationSession) -> list[ConversationTurn]:
    return session.turns[-MAX_RECENT_TURNS_IN_CONTEXT:]
