"""The 11 inspection diagnostic codes.

An inspection diagnostic never implies geometry invalidity on its own —
see docs/bible/16-geometry-inspection/483-inspection-error-model.md. It
means "this specific inspection could not produce a fact," which is
different from "the geometry itself is invalid."
"""

from __future__ import annotations

INSPECTION_COMPONENT_MISSING = "INSPECTION_COMPONENT_MISSING"
INSPECTION_SHAPE_INVALID = "INSPECTION_SHAPE_INVALID"
INSPECTION_VOLUME_FAILED = "INSPECTION_VOLUME_FAILED"
INSPECTION_BOUNDING_BOX_FAILED = "INSPECTION_BOUNDING_BOX_FAILED"
INSPECTION_CONNECTIVITY_FAILED = "INSPECTION_CONNECTIVITY_FAILED"
INSPECTION_INTERSECTION_FAILED = "INSPECTION_INTERSECTION_FAILED"
INSPECTION_DISTANCE_FAILED = "INSPECTION_DISTANCE_FAILED"
INSPECTION_TOPOLOGY_FAILED = "INSPECTION_TOPOLOGY_FAILED"
INSPECTION_KERNEL_UNAVAILABLE = "INSPECTION_KERNEL_UNAVAILABLE"
INSPECTION_UNSUPPORTED = "INSPECTION_UNSUPPORTED"
INSPECTION_INTERNAL_ERROR = "INSPECTION_INTERNAL_ERROR"

ALL_INSPECTION_DIAGNOSTIC_CODES = (
    INSPECTION_COMPONENT_MISSING,
    INSPECTION_SHAPE_INVALID,
    INSPECTION_VOLUME_FAILED,
    INSPECTION_BOUNDING_BOX_FAILED,
    INSPECTION_CONNECTIVITY_FAILED,
    INSPECTION_INTERSECTION_FAILED,
    INSPECTION_DISTANCE_FAILED,
    INSPECTION_TOPOLOGY_FAILED,
    INSPECTION_KERNEL_UNAVAILABLE,
    INSPECTION_UNSUPPORTED,
    INSPECTION_INTERNAL_ERROR,
)
